// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 PT123123 <31439216+PT123123@users.noreply.github.com>

package com.ichi2.anki.lansync

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Recomputes SPEC-v2 §4.6's interoperability vectors with this implementation.
 *
 * `vectors.json` is generated by `anki-desktop/tools/lansync_vectors.py` from the *desktop* crypto
 * and copied into this module's test resources by the same tool. Neither platform can run the
 * other, so these fixed inputs are the only proof that both sides mean the same bytes - if this
 * test fails while the desktop's equivalent passes, pairing between a phone and a desktop is broken
 * and the difference is in the wire format, not in the phone's Wi-Fi.
 *
 * Do not "fix" a failure here by editing this file's expectations: regenerate the vectors from the
 * desktop, and change [LanCrypto] only together with SPEC-v2.
 */
class LanInteropVectorsTest {
    @Serializable
    private class Vectors(
        val inputs: Inputs,
        val pairing: Pairing,
        val envelope: Envelope,
    )

    @Serializable
    private class Inputs(
        @SerialName("contribution_a_hex") val contributionAHex: String,
        @SerialName("contribution_b_hex") val contributionBHex: String,
        @SerialName("device_id_a") val deviceIdA: String,
        @SerialName("device_id_b") val deviceIdB: String,
        @SerialName("nonce_hex") val nonceHex: String,
        @SerialName("pair_code") val pairCode: String,
        @SerialName("plaintext_utf8") val plaintextUtf8: String,
        val route: String,
        val ts: Long,
    )

    @Serializable
    private class Pairing(
        val kid: String,
        @SerialName("pair_wrap_key_hex") val pairWrapKeyHex: String,
        @SerialName("pair_wrapped_contribution_a") val pairWrappedContributionA: LanEnvelope,
        @SerialName("security_code") val securityCode: String,
        @SerialName("shared_secret_hex") val sharedSecretHex: String,
    )

    @Serializable
    private class Envelope(
        val aad: String,
        @SerialName("header_urlsafe_b64") val headerUrlSafeB64: String,
        val json: LanEnvelope,
        @SerialName("route_key_hex") val routeKeyHex: String,
    )

    private val vectors: Vectors by lazy {
        val stream =
            javaClass.getResourceAsStream(RESOURCE)
                ?: throw AssertionError("$RESOURCE is missing - run anki-desktop/tools/lansync_vectors.py")
        stream.use { LanProtocol.json.decodeFromString(Vectors.serializer(), it.readBytes().decodeToString()) }
    }

    @Test
    fun `the two contributions combine into the desktop's shared secret`() {
        val v = vectors
        val shared =
            LanCrypto.combineSecrets(
                own = v.inputs.contributionAHex.hexToBytes(),
                peer = v.inputs.contributionBHex.hexToBytes(),
                ownDeviceId = v.inputs.deviceIdA,
                peerDeviceId = v.inputs.deviceIdB,
            )
        assertEquals(v.pairing.sharedSecretHex, shared.toHex())
        // Swapping the roles must land on the same secret: it is the ordering by device_id that
        // decides, and a phone can be either the initiator or the responder.
        val swapped =
            LanCrypto.combineSecrets(
                own = v.inputs.contributionBHex.hexToBytes(),
                peer = v.inputs.contributionAHex.hexToBytes(),
                ownDeviceId = v.inputs.deviceIdB,
                peerDeviceId = v.inputs.deviceIdA,
            )
        assertEquals(v.pairing.sharedSecretHex, swapped.toHex())
    }

    @Test
    fun `kid and security code match the desktop`() {
        val shared = vectors.pairing.sharedSecretHex.hexToBytes()
        assertEquals(vectors.pairing.kid, LanCrypto.kidOf(shared))
        assertEquals(vectors.pairing.securityCode, LanCrypto.securityCodeOf(shared))
    }

    @Test
    fun `the pairing wrap key matches the desktop`() {
        assertEquals(
            vectors.pairing.pairWrapKeyHex,
            LanCrypto.pairWrapKey(vectors.inputs.pairCode).toHex(),
        )
    }

    @Test
    fun `a wrapped contribution is byte-identical to the desktop's`() {
        val wrapped =
            LanCrypto.wrapSecret(
                pairCode = vectors.inputs.pairCode,
                plain = vectors.inputs.contributionAHex.hexToBytes(),
                nowSeconds = vectors.inputs.ts,
                nonce = vectors.inputs.nonceHex.hexToBytes(),
            )
        assertEquals(vectors.pairing.pairWrappedContributionA, wrapped)
    }

    @Test
    fun `route key, AAD, envelope json and header all match the desktop`() {
        val v = vectors
        val shared = v.pairing.sharedSecretHex.hexToBytes()
        assertEquals(v.envelope.routeKeyHex, LanCrypto.routeKey(shared, v.inputs.route).toHex())
        assertEquals(v.envelope.aad, String(LanCrypto.envelopeAad(v.pairing.kid, v.inputs.ts)))

        val sealed =
            LanCrypto.sealEnvelope(
                deviceSecret = shared,
                route = v.inputs.route,
                kid = v.pairing.kid,
                plaintext = v.inputs.plaintextUtf8.toByteArray(),
                nowSeconds = v.inputs.ts,
                nonce = v.inputs.nonceHex.hexToBytes(),
            )
        // Field-by-field first: a base64 or key-derivation drift shows up here with a readable diff.
        assertEquals(v.envelope.json, sealed)
        // Then the exact bytes the HTTP layer will put into X-Anki-Envelope.
        assertEquals(
            v.envelope.headerUrlSafeB64,
            LanCrypto.base64Url(LanProtocol.json.encodeToString(LanEnvelope.serializer(), sealed)),
        )
    }

    @Test
    fun `the desktop's envelope decrypts here`() {
        val v = vectors
        val opened =
            LanCrypto.openEnvelope(
                deviceSecret = v.pairing.sharedSecretHex.hexToBytes(),
                route = v.inputs.route,
                envelope = v.envelope.json,
                nowSeconds = v.inputs.ts + 60,
                window = LanReplayWindow(),
            )
        assertEquals(v.inputs.plaintextUtf8, opened.decodeToString())
    }

    private fun String.hexToBytes(): ByteArray =
        ByteArray(length / 2) { i ->
            Integer.parseInt(substring(i * 2, i * 2 + 2), 16).toByte()
        }

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }

    private companion object {
        const val RESOURCE = "/lansync/vectors.json"
    }
}
